#!/bin/bash

APPNAME="mx-snapshot"

echodo() {
  echo "${@}"
  ${@}
}

# prepare transifex 
if [ ! -s  .tx/config ]; then
   mkdir -p .tx
   cat <<EOF > .tx/config
[main]
host = https://www.transifex.com

[antix-development.$APPNAME]
file_filter = ./${APPNAME}_<lang>.ts
source_file = ${APPNAME}_en.ts
source_lang = en
type = ts
EOF
fi    

#remove existing translations
backdir="ts_$(date '+%Y-%m-%d_%H%M%S')"
mkdir "$backdir"
mv *.ts "$backdir/"
mv "$backdir/${APPNAME}_en.ts" ./

# get all translations
if command -v tx >/dev/null; then
   echodo tx pull -r antix-development.$APPNAME  --all
fi

